server:
  port: 10086
spring:
  application:
    name: springboot-jpa

  datasource: #数据库相关
    url: jdbc:mysql://localhost:3306/springboot_care_jpa?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: he142536.!
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss #mvc接收参数时对日期进行格式化

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #jackson对响应回去的日期参数进行格式化
    time-zone: GMT+8
  jpa:
    show-sql: true